// --- Array de Proyectos (exportado) alojados en cloudinary.com---
export const projects = [
    { id: 1, category: 'Branding', title: 'Aulas Digitales', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988818/portfolio_branding1_tis9kh.jpg'},
    { id: 2, category: 'Branding', title: 'Club 54', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988819/portfolio_branding2_sjbmjv.jpg' },
    { id: 3, category: 'Branding', title: 'GAV Dermoéstetica', image:'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988820/portfolio_branding3_eco3is.jpg'},
    { id: 4, category: 'Branding', title: 'Laugh & Care', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988822/portfolio_branding5_hwkqfu.jpg'},
    { id: 5, category: 'Branding', title: 'Laugh & Care', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988821/portfolio_branding4_ddclfa.jpg'},
    { id: 6, category: 'Branding', title: 'Marcelo Marino Arquitectura', image:'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988823/portfolio_branding6_uedxgu.jpg'},
    { id: 7, category: 'Branding', title: 'Nomadland ', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988825/portfolio_branding7_fmadxw.jpg'},
    { id: 8, category: 'Branding', title: 'Picadas del Pilar', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988826/portfolio_branding8_jh48eh.jpg' },
    { id: 9, category: 'Branding', title: 'Paw Print', image:'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988827/portfolio_branding9_n6u6to.jpg' },
    { id: 10, category: 'Branding', title: 'RIX', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988828/portfolio_branding10_oa8xjp.jpg'},
    { id: 11, category: 'Branding', title: 'SMID Propiedades', image:'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988830/portfolio_branding11_mtrelo.jpg'},
    { id: 12, category: 'Branding', title: 'Wini ingredientes', image:'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988831/portfolio_branding12_y9vqqs.jpg'},
    { id: 16, category: 'Diseño Gráfico', title: 'Nomadland', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988943/portfolio_folleteria1_rblfsw.jpg' },
    { id: 17, category: 'Diseño Gráfico', title: 'Clover', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988945/portfolio_folleteria2_dhe4ul.jpg'},
    { id: 18, category: 'Diseño Gráfico', title: 'Peponas Cakes', image:' https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988946/portfolio_folleteria3_u46f7e.jpg'},
    { id: 19, category: 'Diseño Gráfico', title: 'Picadas del Pilar', image:'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988948/portfolio_folleteria4_a6jaww.jpg' },
    { id: 20, category: 'Diseño Gráfico', title: 'SMID Propiedades', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988950/portfolio_folleteria5_mmielv.jpg'},
    { id: 21, category: 'Diseño Gráfico', title: 'SMID Propiedades', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988952/portfolio_folleteria6_gw8g3t.jpg' },
    { id: 22, category: 'Diseño Gráfico', title: 'Paw Print', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988953/portfolio_folleteria7_ni7h1o.jpg' },
    { id: 23, category: 'Diseño Gráfico', title: 'Paw Print', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988955/portfolio_folleteria8_ej9wd6.jpg' },
    { id: 24, category: 'Diseño Gráfico', title: 'Paw Print', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988957/portfolio_folleteria9_qxtrmk.jpg' },
    { id: 25, category: 'Diseño Gráfico', title: 'Paw Print', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988959/portfolio_folleteria10_glgt7a.jpg' },
    { id: 26, category: 'Diseño Gráfico', title: 'Paw Print', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988960/portfolio_folleteria11_wk18mt.jpg' },
    { id: 27, category: 'Diseño Gráfico', title: 'Paw Print', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988962/portfolio_folleteria12_n3pask.jpg' },
    { id: 28, category: 'Diseño Gráfico', title: 'Paw Print', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988964/portfolio_folleteria13_pduuhf.jpg' },
    { id: 29, category: 'Diseño Gráfico', title: 'Paw Print', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988966/portfolio_folleteria14_i8oewc.jpg '},
    { id: 31, category: 'Diseño Gráfico', title: 'AMET', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988971/portfolio_folleteria16_uvx5tn.jpg'},
    { id: 32, category: 'Diseño Gráfico', title: 'RIX', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988973/portfolio_folleteria17_nk6fry.jpg '},
    { id: 33, category: 'Diseño Gráfico', title: 'RIX', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988975/portfolio_folleteria18_ecjexl.jpg'},
    { id: 34, category: 'Diseño Gráfico', title: 'RIX', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988978/portfolio_folleteria19_xupakn.jpg'},
    { id: 35, category: 'Diseño Gráfico', title: 'RIX', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988980/portfolio_folleteria20_cqfbma.jpg '},
    { id: 36, category: 'Diseño Gráfico', title: 'RIX', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988984/portfolio_folleteria21_uig24h.jpg' },
    { id: 37, category: 'Diseño Gráfico', title: 'Nomadland', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988986/portfolio_folleteria22_u0ld3r.jpg' },
    { id: 38, category: 'Diseño Gráfico', title: 'Aulas Digitales', image:'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988988/portfolio_folleteria23_axgi4h.jpg'},
    { id: 39, category: 'Diseño Web', title: 'Aulas Digitales', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988877/portfolio_web1_eo2h4i.jpg' },
    { id: 40, category: 'Diseño Web', title: 'SMID Propiedades', image:' https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988878/portfolio_web2_uqsaup.jpg'},
    { id: 41, category: 'Diseño Web', title: 'Rix', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988879/portfolio_web3_igaymw.jpg' },
    { id: 42, category: 'Diseño Web', title: 'MM Ingenieria', image:'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988881/portfolio_web4_xynhtx.jpg' },
    { id: 43, category: 'Diseño Web', title: 'Astra', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988882/portfolio_web5_mvfdqc.jpg'},
    { id: 44, category: 'Diseño Web', title: 'Wini Ingredientes', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988886/portfolio_web6_vcu4a0.jpg' },
    { id: 45, category: 'Diseño Web', title: 'Artistique', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988885/portfolio_web7_kcycuw.jpg'},
    { id: 46, category: 'Diseño Web', title: 'Peponas cakes', image: 'https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988886/portfolio_web8_bcardm.jpg'},
    { id: 47, category: 'Diseño Web', title: 'Paw Print', image:' https://res.cloudinary.com/dosdl7yqj/image/upload/f_auto,q_auto/v1760988888/portfolio_web9_x3axl8.jpg'},
];

// --- Constante de Categorías (exportada) ---
export const categories = ['TODOS', ...new Set(projects.map(p => p.category))];